#!/bin/bash

set -x

find target -name "exdb" | xargs chmod a+x

case "${1}" in
  start)
    for i in {0..2}; do
      "./target/node-0${i}/exdb" start
    done
    ;;

  stop)
    for i in {0..2}; do
      "./target/node-0${i}/exdb" stop
    done
    ;;

  *)
    echo "usage ${0} start"
    echo "      ${0} stop"
    ;;
esac
